version: '3.8'

services:
  goat:
    labels:
      shipyard.route: '/'
    build:
      context: .
    environment:
      NODE_ENV: 'pussy'
    ports:
      - '3001:3001'
    volumes:
      - '.:/usr/src/app'
